DROP TABLE IF EXISTS `kalturadw`.`dwh_dim_kusers`;

CREATE TABLE `kalturadw`.`dwh_dim_kusers` (
  `kuser_id` INT NOT NULL ,
  `screen_name` VARCHAR(20) DEFAULT 'missing value',
  `full_name` VARCHAR(40) DEFAULT 'missing value',
  `email` VARCHAR(50) DEFAULT 'missing value',
  `date_of_birth` DATE DEFAULT NULL,
   location_id INT DEFAULT -1,
   country_id INT DEFAULT -1,
  `zip` VARCHAR(10) DEFAULT NULL,
  `url_list` VARCHAR(256) DEFAULT NULL,
  `picture` VARCHAR(48) DEFAULT NULL,
  `icon` TINYINT DEFAULT NULL,
  `about_me` VARCHAR(4096) DEFAULT NULL,
  `tags` TEXT,
  `tagline` VARCHAR(256) DEFAULT NULL,
  `network_highschool` VARCHAR(30) DEFAULT NULL,
  `network_college` VARCHAR(30) DEFAULT NULL,
  `network_other` VARCHAR(30) DEFAULT NULL,
  `mobile_num` VARCHAR(16) DEFAULT NULL,
  `mature_content` TINYINT DEFAULT '-1',
  `gender_id` TINYINT DEFAULT NULL,
  `gender_name` VARCHAR(7) DEFAULT NULL,
  `registration_ip` INT DEFAULT NULL,
  `registration_cookie` VARCHAR(256) DEFAULT NULL,
  `im_list` VARCHAR(256) DEFAULT NULL,
  `views` INT DEFAULT '0',
  `fans` INT DEFAULT '0',
  `entries` INT DEFAULT '0',
  `produced_kshows` INT DEFAULT '0',
  `kuser_status_id` INT DEFAULT -1,
  `kuser_status_name` VARCHAR(64) DEFAULT 'missing value',
  `created_at` DATETIME DEFAULT NULL,
  `created_date_id` INT DEFAULT '-1',
   created_hour_id TINYINT DEFAULT '-1',
  `updated_at` DATETIME DEFAULT NULL,
   updated_date_id INT DEFAULT '-1',
   updated_hour_id TINYINT DEFAULT '-1',
  `partner_id` INT DEFAULT '-1',
  `display_in_search` TINYINT DEFAULT '1',
  `search_text` VARCHAR(4096) DEFAULT NULL,
  `partner_data` VARCHAR(4096) DEFAULT NULL,
   dwh_creation_date TIMESTAMP NOT NULL DEFAULT 0,
   dwh_update_date TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
   ri_ind TINYINT NOT NULL DEFAULT '0',
   storage_size INT,
   puser_id varchar(64),
   admin_tags text,
   indexed_partner_data_int INT,
   indexed_partner_data_string varchar(64),
  PRIMARY KEY (`kuser_id`),
  KEY `screen_name_index` (`screen_name`),
  KEY `full_name_index` (`full_name`),
  KEY `network_college_index` (`network_college`),
  KEY `network_highschool_index` (`network_highschool`),
  KEY `entries_index` (`entries`),
  KEY `views_index` (`views`),
  KEY `partner_id_index` (`partner_id`,`kuser_id`),
  KEY `partner_created_at_indes` (`partner_id`,`created_at`),
  KEY `created_index` (`created_at`),
  KEY `gender_id` (`gender_id`),
  KEY `kuser_status_id` (`kuser_status_id`),
  KEY `kuser_id_updated_at` (`kuser_id`,`updated_at`),
  KEY `dwh_update_date` (`dwh_update_date`),                                               
  FULLTEXT KEY `search_text_index` (`search_text`)
) ENGINE=MYISAM  DEFAULT CHARSET=utf8;

CREATE TRIGGER `kalturadw`.`dwh_dim_kusers_setcreationtime_oninsert` BEFORE INSERT
    ON `kalturadw`.`dwh_dim_kusers`
    FOR EACH ROW 
	SET new.dwh_creation_date = NOW();
