/*
SQLyog Community Edition- MySQL GUI
MySQL - 5.1.34-community 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `kalturadw`.`ri_defaults` (
	`table_name` varchar (300),
	`default_field` varchar (3000),
	`default_value` varchar (3000)
);

insert into `kalturadw`.`ri_defaults` (`table_name`, `default_field`, `default_value`) 
	values
	('Dwh_Dim_Domains','Domain_name','Missing Value'),
	('Dwh_Dim_Control','Control_name','Missing Value'),
	('Dwh_Dim_Kusers','screen_name','Missing Value'),
	('Dwh_Dim_Kusers','full_name','Missing Value'),
	('Dwh_Dim_Kusers','email','Missing Value'),
	('Dwh_Dim_Kusers','location_id','-1'),
	('Dwh_Dim_Kusers','country_id','-1'),
	('Dwh_Dim_Kusers','gender_id','-1'),
	('Dwh_Dim_Kusers','Kuser_Status_ID','-1'),
	('Dwh_Dim_Kusers','Created_at','2099-01-01 00:00:00'),
	('Dwh_Dim_Kusers','Created_Date_ID','-1'),
	('Dwh_Dim_Kusers','Created_Hour_ID','-1'),
	('Dwh_Dim_Kusers','updated_at','2099-01-01 00:00:00'),
	('Dwh_Dim_Kusers','Updated_Date_ID','-1'),
	('Dwh_Dim_Kusers','Updated_Hour_ID','-1'),
	('Dwh_Dim_Kusers','partner_id','-1'),
	('Dwh_Dim_Entries','kuser_id','-1'),
	('Dwh_Dim_Entries','entry_Type_ID','-1'),
	('Dwh_Dim_Entries','entry_Media_Type_ID','-1'),
	('Dwh_Dim_Entries','views','0'),
	('Dwh_Dim_Entries','votes','0'),
	('Dwh_Dim_Entries','comments','0'),
	('Dwh_Dim_Entries','favorites','0'),
	('Dwh_Dim_Entries','total_rank','0'),
	('Dwh_Dim_Entries','rank','0'),
	('Dwh_Dim_Entries','Entry_Status_ID','-1'),
	('Dwh_Dim_Entries','Entry_media_Source_id','-1'),
	('Dwh_Dim_Entries','entry_source_id','-1'),
	('Dwh_Dim_Entries','entry_license_type_id','-1'),
	('Dwh_Dim_Entries','Created_at','2099-01-01 00:00:00'),
	('Dwh_Dim_Entries','Created_Date_ID','-1'),
	('Dwh_Dim_Entries','Created_Hour_ID','-1'),
	('Dwh_Dim_Entries','updated_at','2099-01-01 00:00:00'),
	('Dwh_Dim_Entries','Updated_Date_ID','-1'),
	('Dwh_Dim_Entries','Updated_Hour_ID','-1'),
	('Dwh_Dim_Entries','partner_id','-1'),
	('Dwh_Dim_Entries','subp_id','-1'),
	('Dwh_Dim_Entries','int_id','-1'),
	('Dwh_Dim_Entries','moderation_status','-1'),
	('Dwh_Dim_Entries','Modified_at','2099-01-01 00:00:00'),
	('Dwh_Dim_Entries','Modified_Date_ID','-1'),
	('Dwh_Dim_Entries','Modified_Hour_ID','-1'),
	('Dwh_Dim_Entry_Type','Entry_Type_Name','Missing Value'),
	('Dwh_Dim_Entry_Media_Type','Entry_Media_Type_Name','Missing Value'),
	('Dwh_Dim_Entry_Media_Source','Entry_Media_Source_Name','Missing Value'),
	('Dwh_Dim_Entry_Status','Entry_Status_Name','Missing Value'),
	('Dwh_Dim_Partners','Partner_Name','Missing Value'),
	('Dwh_Dim_Partners','Created_at','2099-01-01 00:00:00'),
	('Dwh_Dim_Partners','Created_Date_ID','-1'),
	('Dwh_Dim_Partners','Created_Hour_ID','-1'),
	('Dwh_Dim_Partners','updated_at','2099-01-01 00:00:00'),
	('Dwh_Dim_Partners','Updated_Date_ID','-1'),
	('Dwh_Dim_Partners','Updated_Hour_ID','-1'),
	('Dwh_Dim_Partners','ANONYMOUS_KUSER_ID','-1'),
	('Dwh_Dim_Partners','admin_name','Missing Value'),
	('Dwh_Dim_Partners','admin_email','Missing Value'),
	('Dwh_Dim_Partners','description','Missing Value'),
	('Dwh_Dim_Partners','commercial_use','-1'),
	('Dwh_Dim_Partners','moderate_content','-1'),
	('Dwh_Dim_Partners','notify','-1'),
	('Dwh_Dim_Partners','Partner_Status_ID','-1'),
	('Dwh_Dim_Partners','Partner_Status_Name','Missing Value'),
	('Dwh_Dim_Partners','content_categories','Missing Value'),
	('Dwh_Dim_Partners','Partner_Type_ID','-1'),
	('Dwh_Dim_Partners','Partner_Type_Name','Missing Value'),
	('Dwh_Dim_Partners','adult_content','-1'),
	('Dwh_Dim_Partners','partner_package','-1'),
	('Dwh_Dim_UI_Conf','ui_conf_type_id','-1'),
	('Dwh_Dim_UI_Conf','partner_id','-1'),
	('Dwh_Dim_UI_Conf','subp_id','-1'),
	('Dwh_Dim_UI_Conf','created_at','2099-01-01 00:00:00'),
	('Dwh_Dim_UI_Conf','Created_Date_ID','-1'),
	('Dwh_Dim_UI_Conf','Created_Hour_ID','-1'),
	('Dwh_Dim_UI_Conf','updated_at','2099-01-01 00:00:00'),
	('Dwh_Dim_UI_Conf','Updated_Date_ID','-1'),
	('Dwh_Dim_UI_Conf','Updated_Hour_ID','-1'),
	('Dwh_Dim_UI_Conf','UI_Conf_Status_ID','-1'),
	('Dwh_Dim_Widget','partner_id','-1'),
	('Dwh_Dim_Widget','subp_id','-1'),
	('Dwh_Dim_Widget','kshow_id','-1'),
	('Dwh_Dim_Widget','Entry_ID','-1'),
	('Dwh_Dim_Widget','ui_conf_id','-1'),
	('Dwh_Dim_Widget','security_type','-1'),
	('Dwh_Dim_Widget','security_policy','-1'),
	('Dwh_Dim_Widget','Created_at','2099-01-01 00:00:00'),
	('Dwh_Dim_Widget','Created_Date_ID','-1'),
	('Dwh_Dim_Widget','Created_Hour_ID','-1'),
	('Dwh_Dim_Widget','updated_at','2099-01-01 00:00:00'),
	('Dwh_Dim_Widget','Updated_Date_ID','-1'),
	('Dwh_Dim_Widget','Updated_Hour_ID','-1'),
	('Dwh_Dim_UI_conf_type','UI_conf_type_name','Missing Value'),
	('Dwh_Dim_UI_conf_status','UI_conf_status_name','Missing Value'),
	('Dwh_Dim_partner_status','partner_status_name','Missing Value'),
	('Dwh_Dim_partner_type','partner_type_name','Missing Value'),
	('Dwh_Dim_user_status','user_status_name','Missing Value'),
	('Dwh_Dim_moderation_status','moderation_status_name','Missing Value'),
	('Dwh_Dim_partner_sub_activity','partner_sub_activity_name','Missing Value'),
	('Dwh_Dim_partner_activity','partner_activity_name','Missing Value'),
	('Dwh_Dim_widget_security_type','widget_security_type_name','Missing Value'),
	('Dwh_Dim_widget_security_policy','widget_security_policy_name','Missing Value'),
	('Dwh_Dim_Widget','widget_int_id','-1'),
	('Dwh_Dim_partner_group_type','partner_group_type_name','Missing Value'),
	('dwh_dim_asset_status', 'asset_status_name', 'Missing Value'),
	('dwh_dim_flavor_pararms','version', '-1'),
	('dwh_dim_flavor_pararms','partner_id','-1'),
	('dwh_dim_flavor_pararms','NAME','Missing Value'),
	('dwh_dim_flavor_pararms','tags','Missing Value'),
	('dwh_dim_flavor_pararms','description','Missing Value'),
	('dwh_dim_flavor_pararms','ready_behavior','-2'),
	('dwh_dim_flavor_pararms','is_default','-1'),
	('dwh_dim_flavor_pararms','FORMAT','Missing Value'),
	('dwh_dim_flavor_pararms','video_codec','Missing Value'),
	('dwh_dim_flavor_pararms','video_bitrate','-1'),
	('dwh_dim_flavor_pararms','audio_codec','Missing Value'),
	('dwh_dim_flavor_pararms','audio_bitrate','Missing Value'),
	('dwh_dim_flavor_pararms','audio_channels','Missing Value'),
	('dwh_dim_flavor_pararms','audio_sample_rate','-1'),
	('dwh_dim_flavor_pararms','audio_resolution','-1'),
	('dwh_dim_flavor_pararms','width','-1'),
	('dwh_dim_flavor_pararms','height','-1'),
	('dwh_dim_flavor_pararms','frame_rate','-1'),
	('dwh_dim_flavor_pararms','gop_size','-1'),
	('dwh_dim_flavor_pararms','two_pass','-1'),
	('dwh_dim_flavor_pararms','conversion_engines','Missing Value'),
	('dwh_dim_flavor_pararms','conversion_engines_extra_params','Missing Value'),
	('dwh_dim_flavor_pararms','view_order','-1'),
	('dwh_dim_flavor_pararms','bypass_by_extension','Missing Value'),
	('dwh_dim_flavor_pararms','creation_mode','-1'),
	('dwh_dim_flavor_pararms','deinterlice','-1'),
	('dwh_dim_flavor_pararms','rotate','-1'),
	('dwh_dim_flavor_pararms','engine_version','-1'),
	('dwh_dim_flavor_pararms','created_at','2099-01-01 00:00:00'),
	('dwh_dim_flavor_pararms','updated_at','2099-01-01 00:00:00'),
	('dwh_dim_flavor_pararms','deleted_at','2099-01-01 00:00:00'),
	('dwh_dim_ready_behavior', 'ready_behavior_name', 'Missing Value'),
	('dwh_dim_file_sync_object_type', 'file_sync_object_type_name', 'Missing Value'),
	('dwh_dim_file_sync_status', 'file_sync_status_name', 'Missing Value'),
	('dwh_dim_creation_mode', 'creation_mode_name', 'Missing Value'),
	('dwh_dim_conversion_profile', 'partner_id', -1),
	('dwh_dim_conversion_profile', 'name', 'Missing Value'),
	('dwh_dim_conversion_profile', 'created_at', '2099-01-01 00:00:00'),
	('dwh_dim_conversion_profile', 'updated_at', '2099-01-01 00:00:00'),
	('dwh_dim_conversion_profile', 'deleted_at', '2099-01-01 00:00:00'),
	('dwh_dim_conversion_profile', 'clip_start', -1),
	('dwh_dim_conversion_profile', 'clip_duration', -1),
	('dwh_dim_conversion_profile', 'creation_mode', -1),
	('dwh_dim_flavor_asset','int_id','-1'),
	('dwh_dim_flavor_asset','partner_id','-1'),
	('dwh_dim_flavor_asset','entry_id','-1'),
	('dwh_dim_flavor_asset','flavor_params_id','-1'),
	('dwh_dim_flavor_asset','STATUS','-2'),
	('dwh_dim_flavor_asset','VERSION','-1'),
	('dwh_dim_flavor_asset','width','-1'),
	('dwh_dim_flavor_asset','height','-1'),
	('dwh_dim_flavor_asset','bitrate','-1'),
	('dwh_dim_flavor_asset','frame_rate','-1'),
	('dwh_dim_flavor_asset','size','-1'),
	('dwh_dim_flavor_asset','is_original','-1'),
	('dwh_dim_flavor_asset','created_at','2099-01-01 00:00:00'),
	('dwh_dim_flavor_asset','updated_at','2099-01-01 00:00:00'),
	('dwh_dim_flavor_asset','deleted_at','2099-01-01 00:00:00')
;
