CREATE TABLE `kalturadw`.`dwh_aggr_monthly_partner` (
  `partner_id` int NOT NULL DEFAULT '0',
  `month_id` int NOT NULL DEFAULT '0',
  `last_calculated_date_id` int DEFAULT NULL,
  `sum_time_viewed` decimal(20,3) DEFAULT NULL,
  `count_time_viewed` int DEFAULT NULL,
  `count_plays` int DEFAULT NULL,
  `count_loads` int DEFAULT NULL,
  `count_plays_25` int DEFAULT NULL,
  `count_plays_50` int DEFAULT NULL,
  `count_plays_75` int DEFAULT NULL,
  `count_plays_100` int DEFAULT NULL,
  `count_edit` int DEFAULT NULL,
  `count_viral` int DEFAULT NULL,
  `count_download` int DEFAULT NULL,
  `count_report` int DEFAULT NULL,
  `count_media` int DEFAULT NULL,
  `count_video` int DEFAULT NULL,
  `count_image` int DEFAULT NULL,
  `count_audio` int DEFAULT NULL,
  `count_mix` int DEFAULT NULL,
  `count_mix_non_empty` int DEFAULT NULL,
  `count_playlist` int DEFAULT NULL,
  `count_bandwidth` bigint(20) DEFAULT NULL,
  `count_storage` bigint(20) DEFAULT NULL,
  `count_users` int DEFAULT NULL,
  `count_widgets` int DEFAULT NULL,
  `flag_active_site` tinyint(4) DEFAULT '0',
  `flag_active_publisher` tinyint(4) DEFAULT '0',
  `aggr_storage` bigint(20) DEFAULT NULL,
  `aggr_bandwidth` bigint(20) DEFAULT NULL,
  `count_buf_start` int DEFAULT NULL,
  `count_buf_end` int DEFAULT NULL,
  `sum_bandwidth_mb` bigint(20) DEFAULT NULL,
  `sum_storage_mb` bigint(20) DEFAULT NULL,
  `sum_monthly_bandwidth_mb` bigint(20) DEFAULT NULL,
  `calculated_storage_mb` bigint(20) DEFAULT NULL,
  `calculated_monthly_storage_mb` bigint(20) DEFAULT NULL,
  `count_open_full_screen` int DEFAULT NULL,
  `count_close_full_screen` int DEFAULT NULL,
  `count_replay` int DEFAULT NULL,
  `count_seek` int DEFAULT NULL,
  `count_open_upload` int DEFAULT NULL,
  `count_save_publish` int DEFAULT NULL,
  `count_close_editor` int DEFAULT NULL,
  `count_pre_bumper_played` INT DEFAULT NULL,
  `count_post_bumper_played` INT DEFAULT NULL,
  `count_bumper_clicked` INT DEFAULT NULL,
  `count_preroll_started` INT DEFAULT NULL,
  `count_midroll_started` INT DEFAULT NULL,
  `count_postroll_started` INT DEFAULT NULL,
  `count_overlay_started` INT DEFAULT NULL,
  `count_preroll_clicked` INT DEFAULT NULL,
  `count_midroll_clicked` INT DEFAULT NULL,
  `count_postroll_clicked` INT DEFAULT NULL,
  `count_overlay_clicked` INT DEFAULT NULL,
  `count_preroll_25` INT DEFAULT NULL,
  `count_preroll_50` INT DEFAULT NULL,
  `count_preroll_75` INT DEFAULT NULL,
  `count_midroll_25` INT DEFAULT NULL,
  `count_midroll_50` INT DEFAULT NULL,
  `count_midroll_75` INT DEFAULT NULL,
  `count_postroll_25` INT DEFAULT NULL,
  `count_postroll_50` INT DEFAULT NULL,
  `count_postroll_75` INT DEFAULT NULL,
  PRIMARY KEY (`partner_id`,`month_id`),
  KEY `month_id` (`month_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8
/*!50100 PARTITION BY RANGE (month_id)
(PARTITION p_2009 VALUES LESS THAN (201001) ENGINE = MyISAM,
 PARTITION p_2010 VALUES LESS THAN (201101) ENGINE = MyISAM,
 PARTITION p_2011 VALUES LESS THAN (201201) ENGINE = MyISAM,
 PARTITION p_2012 VALUES LESS THAN (201301) ENGINE = MyISAM) */