# KALTURA-INSTALL
#all:
#  propel:
#    class:          sfPropelDatabase
#    param:
#      dsn:          mysql://root:@localhost/dbname


prod: 
  propel: 
    param: 
      host:               @DB1_HOST@:@DB1_PORT@
      database:           @DB1_NAME@
      username:           @DB1_USER@ 
      password:           @DB1_PASS@
#      persistent:         true
#      pooling:            true      
      
  propel2: 
    param: 
      host:               @DB2_HOST@:@DB2_PORT@
      database:           @DB2_NAME@
      username:           @DB2_USER@
      password:           @DB2_PASS@
      datasource:       propel2
#      persistent:         true
#      pooling:            true      
      
            
  propel3: 
    param: 
      host:               @DB3_HOST@:@DB3_PORT@
      database:           @DB3_NAME@
      username:           @DB3_USER@
      password:           @DB3_PASS@
      datasource:       propel3
#      persistent:         true
#      pooling:            true      
      
            
  kaltura_stats: 
    param: 
      host:               @DB_STATS_HOST@:@DB_STATS_PORT@
      database:           @DB_STATS_NAME@
      username:           @DB_STATS_USER@
      password:           @DB_STATS_PASS@
      datasource:       kaltura_stats
#      persistent:         true
#      pooling:            true      
      
            
all: 
  propel: 
    class:                sfPropelDatabase 
    param: 
      phptype:            mysql
      host:               @DB1_HOST@:@DB1_PORT@
      database:           @DB1_NAME@
      username:           @DB1_USER@
      password:           @DB1_PASS@
      compat_assoc_lower: true
      datasource:       propel
#      persistent:         true
#      pooling:            true      
      
      
  propel2: 
    class:                sfPropelDatabase 
    param: 
      phptype:            mysql
      host:               @DB2_HOST@:@DB2_PORT@
      database:           @DB2_NAME@
      username:           @DB2_USER@
      password:           @DB2_PASS@
      compat_assoc_lower: true
      datasource:       propel2
#      persistent:         true
#      pooling:            true      
      
      
  propel3: 
    class:                sfPropelDatabase 
    param: 
      phptype:            mysql
      host:               @DB3_HOST@:@DB3_PORT@
      database:           @DB3_NAME@
      username:           @DB3_USER@
      password:           @DB3_PASS@
      compat_assoc_lower: true
      datasource:       propel3
#      persistent:         true
#      pooling:            true      
      
  kaltura_stats: 
    class:                sfPropelDatabase 
    param: 
      phptype:            mysql
      host:               @DB_STATS_HOST@:@DB_STATS_PORT@
      database:           @DB_STATS_NAME@
      username:           @DB_STATS_USER@
      password:           @DB_STATS_PASS@
      compat_assoc_lower: true
      datasource:       kaltura_stats
#      persistent:         true
#      pooling:            true      
      