DROP TABLE IF EXISTS `kalturadw`.dwh_dim_entries;


CREATE TABLE `kalturadw`.dwh_dim_entries (                                                                              
          `entry_id` VARCHAR(20) NOT NULL,                                                                        
          `kshow_id` VARCHAR(20) DEFAULT NULL,                                                              
          `kuser_id` INT DEFAULT -1,                                                                  
          `entry_name` VARCHAR(60) DEFAULT NULL,                                                                  
          `entry_type_id` SMALLINT DEFAULT NULL,                                                                  
          `entry_media_type_id` SMALLINT DEFAULT NULL,                                                            
          `data` VARCHAR(48) DEFAULT NULL,                                                                  
          `thumbnail` VARCHAR(48) DEFAULT NULL,                                                             
          `views` INT DEFAULT '0',                                                                      
          `votes` INT DEFAULT '0',                                                                      
          `comments` INT DEFAULT '0',                                                                   
          `favorites` INT DEFAULT '0',                                                                  
          `total_rank` INT DEFAULT '0',                                                                 
          `rank` INT DEFAULT '0',                                                                       
          `tags` TEXT,                                                                                      
          `anonymous` TINYINT DEFAULT NULL,                                                              
          `entry_status_id` SMALLINT DEFAULT -1,                                                                    
          `entry_media_source_id` SMALLINT DEFAULT -1,                                                                
          `entry_source_id` VARCHAR(48) DEFAULT -1,                                                                 
          `source_link` VARCHAR(1024) DEFAULT NULL,                                                         
          `entry_license_type_id` SMALLINT DEFAULT -1,                                                          
          `credit` VARCHAR(1024) DEFAULT NULL,                                                              
          `length_in_msecs` INT DEFAULT '0', 
           height  INT DEFAULT NULL,
           width  INT DEFAULT NULL,
           conversion_quality VARCHAR(50) DEFAULT NULL,
           storage_size BIGINT DEFAULT NULL, 
           editor_type_id  SMALLINT DEFAULT -1,  
		   puser_id VARCHAR(64) DEFAULT NULL,
		   is_admin_content TINYINT, 
	  `created_at` DATETIME DEFAULT NULL,
	  `created_date_id` INT DEFAULT '-1',
	   created_hour_id TINYINT DEFAULT '-1',
	  `updated_at` DATETIME DEFAULT NULL,
           updated_date_id INT DEFAULT '-1',
	   updated_hour_id TINYINT DEFAULT '-1',                                                             
          `partner_id` INT DEFAULT -1,                                                                 
          `display_in_search` TINYINT,                                                       
          `subp_id` INT DEFAULT -1,                                                                    
          `custom_data` TEXT,                                                                               
          `search_text` VARCHAR(4096) DEFAULT NULL,                                                         
          `screen_name` VARCHAR(20) DEFAULT NULL,                                                           
          `site_url` VARCHAR(256) DEFAULT NULL,
                                                                      
          `permissions` INT DEFAULT NULL,                                                               
          `group_id` VARCHAR(64) DEFAULT NULL,                                                              
          `plays` INT DEFAULT '0',                                                                      
          `partner_data` VARCHAR(4096) DEFAULT NULL,                                                        
          `int_id` INT NOT NULL,                                                         
          `indexed_custom_data_1` INT DEFAULT NULL,                                                     
          `description` TEXT,                                                                               
          `media_date` DATETIME DEFAULT NULL,                                                               
          `admin_tags` TEXT,                                                                                
          `moderation_status` TINYINT DEFAULT -1,                                                          
          `moderation_count` INT ,                                                           
          `modified_at` DATETIME DEFAULT NULL,   
           modified_date_id INT DEFAULT '-1',
	   modified_hour_id TINYINT DEFAULT '-1',  
	   dwh_creation_date TIMESTAMP NOT NULL DEFAULT 0,
	   dwh_update_date TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
 	   ri_ind TINYINT NOT NULL DEFAULT '0'  ,                                                       
          PRIMARY KEY (`entry_id`),                                                                               
          KEY `partner_id_created_media_type_source` (`partner_id`,`created_at`,entry_media_type_id,entry_media_source_id),                                       
	  KEY `dwh_update_date` (`dwh_update_date`), 
	  KEY `entry_id_modified_at` (entry_id,modified_at),                                              
	  KEY `entry_id_name` (entry_id,entry_name),                                              
	  KEY `entry_id_media_type` (entry_id,entry_media_type_id),
#          FULLTEXT KEY `search_text_index` (`search_text`),
		  FULLTEXT KEY all_text (entry_name,description,tags,admin_tags),  
		  FULLTEXT KEY admin_tags_text (admin_tags)
        ) ENGINE=MYISAM  DEFAULT CHARSET=utf8   ;
        
CREATE TRIGGER `kalturadw`.`dwh_dim_entries_setcreationtime_oninsert` BEFORE INSERT
    ON `kalturadw`.`dwh_dim_entries`
    FOR EACH ROW 
	SET new.dwh_creation_date = NOW();  