<?php

// Kaltuara Installer folders definitions

DEFINE('CONFIG_DIR',  dirname(__FILE__).DIRECTORY_SEPARATOR);
DEFINE('LIB_DIR',     dirname(__FILE__).DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'lib'.DIRECTORY_SEPARATOR);
DEFINE('STEPS_DIR',   dirname(__FILE__).DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'steps'.DIRECTORY_SEPARATOR);
DEFINE('PACKAGE_DIR', dirname(__FILE__).DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'package'.DIRECTORY_SEPARATOR);
DEFINE('TMP_DIR',   dirname(__FILE__).DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'tmp'.DIRECTORY_SEPARATOR);
DEFINE('INSTALL_CONFIG_FILE', dirname(__FILE__).DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'my_config.ini');
DEFINE('UNINSTALLER_DIR', dirname(__FILE__).DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'uninstaller'.DIRECTORY_SEPARATOR);
DEFINE('DONE_STEPS', CONFIG_DIR.'../done_steps.txt');
DEFINE('PREREQUISITES_FILE', CONFIG_DIR.'prerequisites.php');
DEFINE('INSTALL_ERROR_LOG', dirname(__FILE__).DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'install-log.txt');
DEFINE('INSTALL_REPORT_URL', 'http://kalstats.kaltura.com/index.php/events/installation_event');

require_once(PACKAGE_DIR.'package_folders.php');