default:
  has_layout:     on
  layout:         kmclayout
  javascripts:    [ jqkaltura.js, /lib/js/modal , /lib/js/common , /lib/js/functions.js , http://ajax.googleapis.com/ajax/libs/swfobject/2.1/swfobject.js ]
  stylesheets:  [ /lib/css/modal, /lib/css/kmc ]  
  
