/* Find different or missing rows*/
SELECT IFNULL(tagline,''),IFNULL(kuser_status_id,''),IFNULL(zip,''),IFNULL(views,''),IFNULL(url_list,''),IFNULL(screen_name,''),IFNULL(search_text,''),IFNULL(tags,''),IFNULL(updated_at,''),IFNULL(registration_ip,''),IFNULL(registration_cookie,''),IFNULL(produced_kshows,''),IFNULL(picture,''),IFNULL(partner_id,''),IFNULL(partner_data,''),IFNULL(network_other,''),IFNULL(network_highschool,''),IFNULL(network_college,''),IFNULL(mobile_num,''),IFNULL(mature_content,''),IFNULL(im_list,''),kuser_id,IFNULL(icon,''),IFNULL(gender_id,''),IFNULL(full_name,''),IFNULL(fans,''),IFNULL(entries,''),IFNULL(email,''),IFNULL(display_in_search,''),IFNULL(date_of_birth,''),IFNULL(created_at,''),IFNULL(about_me,'') 
FROM kalturadw.dwh_dim_kusers
 WHERE (IFNULL(tagline,''),IFNULL(kuser_status_id,''),IFNULL(zip,''),IFNULL(views,''),IFNULL(url_list,''),IFNULL(screen_name,''),IFNULL(search_text,''),IFNULL(tags,''),IFNULL(updated_at,''),IFNULL(registration_ip,''),IFNULL(registration_cookie,''),IFNULL(produced_kshows,''),IFNULL(picture,''),IFNULL(partner_id,''),IFNULL(partner_data,''),IFNULL(network_other,''),IFNULL(network_highschool,''),IFNULL(network_college,''),IFNULL(mobile_num,''),IFNULL(mature_content,''),IFNULL(im_list,''),kuser_id,IFNULL(icon,''),IFNULL(gender_id,''),IFNULL(full_name,''),IFNULL(fans,''),IFNULL(entries,''),IFNULL(email,''),IFNULL(display_in_search,''),IFNULL(date_of_birth,''),IFNULL(created_at,''),IFNULL(about_me,'')) 
NOT IN (SELECT IFNULL(tagline,''),IF(STATUS IS NULL OR CAST(STATUS AS CHAR)='','-1',STATUS),IFNULL(zip,''),IFNULL(views,''),IFNULL(url_list,''),IF(screen_name IS NULL OR CAST(screen_name AS CHAR)='','Missing Value',screen_name),IFNULL(search_text,''),IFNULL(tags,''),IF(updated_at IS NULL OR CAST(updated_at AS CHAR)='','2099-01-01 00:00:00',updated_at),IFNULL(registration_ip,''),IFNULL(registration_cookie,''),IFNULL(produced_kshows,''),IFNULL(picture,''),IF(partner_id IS NULL OR CAST(partner_id AS CHAR)='','-1',partner_id),IFNULL(partner_data,''),IFNULL(network_other,''),IFNULL(network_highschool,''),IFNULL(network_college,''),IFNULL(mobile_num,''),IFNULL(mature_content,''),IFNULL(im_list,''),id,IFNULL(icon,''),IF(gender IS NULL OR CAST(gender AS CHAR)='','-1',gender),IF(full_name IS NULL OR CAST(full_name AS CHAR)='','Missing Value',full_name),IFNULL(fans,''),IFNULL(entries,''),IF(email IS NULL OR CAST(email AS CHAR)='','Missing Value',email),IFNULL(display_in_search,''),IFNULL(date_of_birth,''),IF(created_at IS NULL OR CAST(created_at AS CHAR)='','2099-01-01 00:00:00',created_at),IFNULL(about_me,'')
		FROM kaltura.kuser)
UNION ALL 
 SELECT IFNULL(tagline,''),IF(STATUS IS NULL OR CAST(STATUS AS CHAR)='','-1',STATUS),IFNULL(zip,''),IFNULL(views,''),IFNULL(url_list,''),IF(screen_name IS NULL OR CAST(screen_name AS CHAR)='','Missing Value',screen_name),IFNULL(search_text,''),IFNULL(tags,''),IF(updated_at IS NULL OR CAST(updated_at AS CHAR)='','2099-01-01 00:00:00',updated_at),IFNULL(registration_ip,''),IFNULL(registration_cookie,''),IFNULL(produced_kshows,''),IFNULL(picture,''),IF(partner_id IS NULL OR CAST(partner_id AS CHAR)='','-1',partner_id),IFNULL(partner_data,''),IFNULL(network_other,''),IFNULL(network_highschool,''),IFNULL(network_college,''),IFNULL(mobile_num,''),IFNULL(mature_content,''),IFNULL(im_list,''),id,IFNULL(icon,''),IF(gender IS NULL OR CAST(gender AS CHAR)='','-1',gender),IF(full_name IS NULL OR CAST(full_name AS CHAR)='','Missing Value',full_name),IFNULL(fans,''),IFNULL(entries,''),IF(email IS NULL OR CAST(email AS CHAR)='','Missing Value',email),IFNULL(display_in_search,''),IFNULL(date_of_birth,''),IF(created_at IS NULL OR CAST(created_at AS CHAR)='','2099-01-01 00:00:00',created_at),IFNULL(about_me,'') 
FROM kaltura.kuser
 WHERE (IFNULL(tagline,''),IF(STATUS IS NULL OR CAST(STATUS AS CHAR)='','-1',STATUS),IFNULL(zip,''),IFNULL(views,''),IFNULL(url_list,''),IF(screen_name IS NULL OR CAST(screen_name AS CHAR)='','Missing Value',screen_name),IFNULL(search_text,''),IFNULL(tags,''),IF(updated_at IS NULL OR CAST(updated_at AS CHAR)='','2099-01-01 00:00:00',updated_at),IFNULL(registration_ip,''),IFNULL(registration_cookie,''),IFNULL(produced_kshows,''),IFNULL(picture,''),IF(partner_id IS NULL OR CAST(partner_id AS CHAR)='','-1',partner_id),IFNULL(partner_data,''),IFNULL(network_other,''),IFNULL(network_highschool,''),IFNULL(network_college,''),IFNULL(mobile_num,''),IFNULL(mature_content,''),IFNULL(im_list,''),id,IFNULL(icon,''),IF(gender IS NULL OR CAST(gender AS CHAR)='','-1',gender),IF(full_name IS NULL OR CAST(full_name AS CHAR)='','Missing Value',full_name),IFNULL(fans,''),IFNULL(entries,''),IF(email IS NULL OR CAST(email AS CHAR)='','Missing Value',email),IFNULL(display_in_search,''),IFNULL(date_of_birth,''),IF(created_at IS NULL OR CAST(created_at AS CHAR)='','2099-01-01 00:00:00',created_at),IFNULL(about_me,''))
 NOT IN (SELECT IFNULL(tagline,''),IFNULL(kuser_status_id,''),IFNULL(zip,''),IFNULL(views,''),IFNULL(url_list,''),IFNULL(screen_name,''),IFNULL(search_text,''),IFNULL(tags,''),IFNULL(updated_at,''),IFNULL(registration_ip,''),IFNULL(registration_cookie,''),IFNULL(produced_kshows,''),IFNULL(picture,''),IFNULL(partner_id,''),IFNULL(partner_data,''),IFNULL(network_other,''),IFNULL(network_highschool,''),IFNULL(network_college,''),IFNULL(mobile_num,''),IFNULL(mature_content,''),IFNULL(im_list,''),kuser_id,IFNULL(icon,''),IFNULL(gender_id,''),IFNULL(full_name,''),IFNULL(fans,''),IFNULL(entries,''),IFNULL(email,''),IFNULL(display_in_search,''),IFNULL(date_of_birth,''),IFNULL(created_at,''),IFNULL(about_me,'')
		FROM kalturadw.dwh_dim_kusers)
ORDER BY kuser_id;
