/* Find different or missing rows*/
SELECT IFNULL(updated_at,''),IFNULL(ui_conf_id,''),IFNULL(subp_id,''),IFNULL(source_widget_id,''),IFNULL(security_type,''),IFNULL(security_policy,''),IFNULL(root_widget_id,''),IFNULL(partner_id,''),IFNULL(kshow_id,''),IFNULL(widget_int_id,''),widget_id,IFNULL(entry_id,''),IFNULL(custom_data,''),IFNULL(created_at,'') 
FROM kalturadw.dwh_dim_widget
 WHERE (IFNULL(updated_at,''),IFNULL(ui_conf_id,''),IFNULL(subp_id,''),IFNULL(source_widget_id,''),IFNULL(security_type,''),IFNULL(security_policy,''),IFNULL(root_widget_id,''),IFNULL(partner_id,''),IFNULL(kshow_id,''),IFNULL(widget_int_id,''),widget_id,IFNULL(entry_id,''),IFNULL(custom_data,''),IFNULL(created_at,'')) 
NOT IN (SELECT IF(updated_at IS NULL OR CAST(updated_at AS CHAR)='','2099-01-01 00:00:00',updated_at),IF(ui_conf_id IS NULL OR CAST(ui_conf_id AS CHAR)='','-1',ui_conf_id),IF(subp_id IS NULL OR CAST(subp_id AS CHAR)='','-1',subp_id),IFNULL(source_widget_id,''),IF(security_type IS NULL OR CAST(security_type AS CHAR)='','-1',security_type),IF(security_policy IS NULL OR CAST(security_policy AS CHAR)='','-1',security_policy),IFNULL(root_widget_id,''),IF(partner_id IS NULL OR CAST(partner_id AS CHAR)='','-1',partner_id),IF(kshow_id IS NULL OR CAST(kshow_id AS CHAR)='','-1',kshow_id),IF(int_id IS NULL OR CAST(int_id AS CHAR)='','-1',int_id),id,IF(entry_id IS NULL OR CAST(entry_id AS CHAR)='','-1',entry_id),IFNULL(custom_data,''),IF(created_at IS NULL OR CAST(created_at AS CHAR)='','2099-01-01 00:00:00',created_at)
		FROM kaltura.widget)
UNION ALL 
 SELECT IF(updated_at IS NULL OR CAST(updated_at AS CHAR)='','2099-01-01 00:00:00',updated_at),IF(ui_conf_id IS NULL OR CAST(ui_conf_id AS CHAR)='','-1',ui_conf_id),IF(subp_id IS NULL OR CAST(subp_id AS CHAR)='','-1',subp_id),IFNULL(source_widget_id,''),IF(security_type IS NULL OR CAST(security_type AS CHAR)='','-1',security_type),IF(security_policy IS NULL OR CAST(security_policy AS CHAR)='','-1',security_policy),IFNULL(root_widget_id,''),IF(partner_id IS NULL OR CAST(partner_id AS CHAR)='','-1',partner_id),IF(kshow_id IS NULL OR CAST(kshow_id AS CHAR)='','-1',kshow_id),IF(int_id IS NULL OR CAST(int_id AS CHAR)='','-1',int_id),id,IF(entry_id IS NULL OR CAST(entry_id AS CHAR)='','-1',entry_id),IFNULL(custom_data,''),IF(created_at IS NULL OR CAST(created_at AS CHAR)='','2099-01-01 00:00:00',created_at) 
FROM kaltura.widget
 WHERE (IF(updated_at IS NULL OR CAST(updated_at AS CHAR)='','2099-01-01 00:00:00',updated_at),IF(ui_conf_id IS NULL OR CAST(ui_conf_id AS CHAR)='','-1',ui_conf_id),IF(subp_id IS NULL OR CAST(subp_id AS CHAR)='','-1',subp_id),IFNULL(source_widget_id,''),IF(security_type IS NULL OR CAST(security_type AS CHAR)='','-1',security_type),IF(security_policy IS NULL OR CAST(security_policy AS CHAR)='','-1',security_policy),IFNULL(root_widget_id,''),IF(partner_id IS NULL OR CAST(partner_id AS CHAR)='','-1',partner_id),IF(kshow_id IS NULL OR CAST(kshow_id AS CHAR)='','-1',kshow_id),IF(int_id IS NULL OR CAST(int_id AS CHAR)='','-1',int_id),id,IF(entry_id IS NULL OR CAST(entry_id AS CHAR)='','-1',entry_id),IFNULL(custom_data,''),IF(created_at IS NULL OR CAST(created_at AS CHAR)='','2099-01-01 00:00:00',created_at))
 NOT IN (SELECT IFNULL(updated_at,''),IFNULL(ui_conf_id,''),IFNULL(subp_id,''),IFNULL(source_widget_id,''),IFNULL(security_type,''),IFNULL(security_policy,''),IFNULL(root_widget_id,''),IFNULL(partner_id,''),IFNULL(kshow_id,''),IFNULL(widget_int_id,''),widget_id,IFNULL(entry_id,''),IFNULL(custom_data,''),IFNULL(created_at,'')
		FROM kalturadw.dwh_dim_widget)
ORDER BY widget_id;
