default:
  has_layout:   on
  layout:       kmclayout
  javascripts:  [ http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js , http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js , /lib/js/modal.js , /lib/js/scripts.js ]
  stylesheets:  [ /lib/css/modal, /lib/css/kmc ]

kmc1Success:
  has_layout:     on
  layout:         kmc1layout
  javascripts:    [ -*, jqkaltura.js, /lib/js/kmc1modal , /lib/js/common , /lib/js/functions.js , http://ajax.googleapis.com/ajax/libs/swfobject/2.1/swfobject.js ]
  stylesheets:  [ -*, /lib/css/kmc1modal, /lib/css/kmc1 ]
  
varpartnerlistSuccess:
  has_layout:     on
  layout:         kmc1layout
  javascripts:    [ -*, jqkaltura.js, /lib/js/kmc1modal , /lib/js/common , /lib/js/functions.js , http://ajax.googleapis.com/ajax/libs/swfobject/2.1/swfobject.js ]
  stylesheets:  [ -*, /lib/css/kmc1modal, /lib/css/kmc1 ]
  

#	jqkaltura.js:
#  * jQuery 1.2.1 + Macromedia(r) Flash(r) JavaScript Integration Kit
#  * kaltura/OLD_PATHS/web/js

supportSuccess:
  has_layout:     off
  layout:         kmc1layout
  javascripts:    [ -*, http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js ]
  stylesheets:    [ -* ]

helpSuccess:
  has_layout:     on
  layout:         helplayout
  javascripts:    [ -* ]
  stylesheets:    [ -*, /lib/css/kmc ]

kmc2helpSuccess:
  has_layout:     on
  layout:         helplayout
  javascripts:    [ -*, http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js ]
  stylesheets:    [ -*, /lib/css/kmc ]